core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("forms/", include(("dynamic_forms.urls", "dynamic_forms"), namespace="forms")),
]

dynamic_forms/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new-form/', views.FormBuilderView.as_view(), name='new-form'),
    path('edit-form/<form_id>/', views.EditFormView.as_view(), name='edit-form'),
    path('forms-list/', views.FormListView.as_view(), name='forms-list'),
    path('form/<str:form_id>/', views.RenderFormView.as_view(), name='form'),
    # fetch requests
    path('get-form/', views.get_form, name='get-form'),
    path('get-model-form/', views.get_model_form, name='get-model-form'),
    path('save-form/', views.save_form, name='save-form'),
    path('get-form-layout/', views.get_form_layout, name='get-form-layout'),
    # tinymce url
    path('tinymce/', include('tinymce.urls')),
]

dynamic_forms/models/forms.py
from django.db import models


# form field types
class FormModel(models.Model):
    form_id = models.CharField(max_length=255, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True, help_text="The name of the form")
    description = models.TextField(blank=True, null=True, help_text="Form description")
    for_table = models.BooleanField(default=False, help_text="Create a form for a database table")
    table = models.CharField(max_length=255, blank=True, null=True, help_text="Name of the table")
    layout = models.TextField(blank=True, null=True, help_text="Form layout")
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

dynamic_forms/forms.py
from django import forms
from django.apps import apps
from django.forms import modelformset_factory, ModelForm
from django.conf import settings

from tinymce.widgets import TinyMCE

from .models import (TextInput, TextAreaInput, EmailInput, DateInput, DateTimeInput, DropDownInput,
                     MultipleSelectDropDownInput, IntegerInput, DecimalInput, CheckboxInput, RadioInput,
                     FileInput, FormModel, FormRow, DividerLine, SectionHeader, TextBlock, CollapsibleSection,
                     HorizontalRule)


# ***** Form Field Forms *****
class TextInputField(ModelForm):
    class Meta:
        model = TextInput
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(TextInputField, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            # adding valueChanged dataset attribute
            visible.field.widget.attrs["data-value-changed"] = "false"
            visible.field.widget.attrs["data-model-field"] = "false"

            if visible.widget_type == "text" or visible.widget_type == "number":
                visible.field.widget.attrs["class"] = "form-control"
            elif visible.widget_type == "date":
                visible.field.widget = forms.DateInput(attrs={"class": "form-control", "type": "date"})
            elif visible.widget_type == "datetime":
                visible.field.widget = forms.DateTimeInput(attrs={"class": "form-control", "type": "datetime"})
            elif visible.widget_type == "select" or visible.widget_type == "nullbooleanselect":
                visible.field.widget.attrs["class"] = "form-select"
            elif visible.widget_type == "textarea":
                visible.field.widget.attrs["class"] = "form-control"
                visible.field.widget.attrs["rows"] = 5
            elif visible.widget_type == "checkbox":
                visible.field.widget.attrs["class"] = "form-check-input"


class TextAreaField(ModelForm):
    class Meta:
        model = TextAreaInput
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(TextAreaField, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            # adding valueChanged dataset attribute
            visible.field.widget.attrs["data-value-changed"] = "false"
            visible.field.widget.attrs["data-model-field"] = "false"

            if visible.widget_type == "text" or visible.widget_type == "number":
                visible.field.widget.attrs["class"] = "form-control"
            elif visible.widget_type == "date":
                visible.field.widget = forms.DateInput(attrs={"class": "form-control", "type": "date"})
            elif visible.widget_type == "datetime":
                visible.field.widget = forms.DateTimeInput(attrs={"class": "form-control", "type": "datetime"})
            elif visible.widget_type == "select" or visible.widget_type == "nullbooleanselect":
                visible.field.widget.attrs["class"] = "form-select"
            elif visible.widget_type == "textarea":
                visible.field.widget.attrs["class"] = "form-control"
                visible.field.widget.attrs["rows"] = 5
            elif visible.widget_type == "checkbox":
                visible.field.widget.attrs["class"] = "form-check-input"


class EmailInputField(ModelForm):
    class Meta:
        model = EmailInput
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EmailInputField, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            # adding valueChanged dataset attribute
            visible.field.widget.attrs["data-value-changed"] = "false"
            visible.field.widget.attrs["data-model-field"] = "false"

            if visible.widget_type == "text" or visible.widget_type == "number":
                visible.field.widget.attrs["class"] = "form-control"
            elif visible.widget_type == "date":
                visible.field.widget = forms.DateInput(attrs={"class": "form-control", "type": "date"})
            elif visible.widget_type == "datetime":
                visible.field.widget = forms.DateTimeInput(attrs={"class": "form-control", "type": "datetime"})
            elif visible.widget_type == "select" or visible.widget_type == "nullbooleanselect":
                visible.field.widget.attrs["class"] = "form-select"
            elif visible.widget_type == "textarea":
                visible.field.widget.attrs["class"] = "form-control"
                visible.field.widget.attrs["rows"] = 5
            elif visible.widget_type == "checkbox":
                visible.field.widget.attrs["class"] = "form-check-input"


class DateInputField(ModelForm):
    class Meta:
        model = DateInput
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(DateInputField, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            # adding valueChanged dataset attribute
            visible.field.widget.attrs["data-value-changed"] = "false"
            visible.field.widget.attrs["data-model-field"] = "false"

            if visible.widget_type == "text" or visible.widget_type == "number":
                visible.field.widget.attrs["class"] = "form-control"
            elif visible.widget_type == "date":
                visible.field.widget = forms.DateInput(attrs={"class": "form-control", "type": "date"})
            elif visible.widget_type == "datetime":
                visible.field.widget = forms.DateTimeInput(attrs={"class": "form-control", "type": "datetime"})
            elif visible.widget_type == "select" or visible.widget_type == "nullbooleanselect":
                visible.field.widget.attrs["class"] = "form-select"
            elif visible.widget_type == "textarea":
                visible.field.widget.attrs["class"] = "form-control"
                visible.field.widget.attrs["rows"] = 5
            elif visible.widget_type == "checkbox":
                visible.field.widget.attrs["class"] = "form-check-input"


class DateTimeInputField(ModelForm):
    class Meta:
        model = DateTimeInput
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(DateTimeInputField, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            # adding valueChanged dataset attribute
            visible.field.widget.attrs["data-value-changed"] = "false"
            visible.field.widget.attrs["data-model-field"] = "false"

            if visible.widget_type == "text" or visible.widget_type == "number":
                visible.field.widget.attrs["class"] = "form-control"
            elif visible.widget_type == "date":
                visible.field.widget = forms.DateInput(attrs={"class": "form-control", "type": "date"})
            elif visible.widget_type == "datetime":
                visible.field.widget = forms.DateTimeInput(attrs={"class": "form-control", "type": "datetime"})
            elif visible.widget_type == "select" or visible.widget_type == "nullbooleanselect":
                visible.field.widget.attrs["class"] = "form-select"
            elif visible.widget_type == "textarea":
                visible.field.widget.attrs["class"] = "form-control"
                visible.field.widget.attrs["rows"] = 5
            elif visible.widget_type == "checkbox":
                visible.field.widget.attrs["class"] = "form-check-input"


class DropDownField(ModelForm):
    class Meta:
        model = DropDownInput
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(DropDownField, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            # adding valueChanged dataset attribute
            visible.field.widget.attrs["data-value-changed"] = "false"
            visible.field.widget.attrs["data-model-field"] = "false"

            if visible.widget_type == "text" or visible.widget_type == "number":
                visible.field.widget.attrs["class"] = "form-control"
            elif visible.widget_type == "date":
                visible.field.widget = forms.DateInput(attrs={"class": "form-control", "type": "date"})
            elif visible.widget_type == "datetime":
                visible.field.widget = forms.DateTimeInput(attrs={"class": "form-control", "type": "datetime"})
            elif visible.widget_type == "select" or visible.widget_type == "nullbooleanselect":
                visible.field.widget.attrs["class"] = "form-select"
            elif visible.widget_type == "textarea":
                visible.field.widget.attrs["class"] = "form-control"
                visible.field.widget.attrs["rows"] = 5
            elif visible.widget_type == "checkbox":
                visible.field.widget.attrs["class"] = "form-check-input"


class MultipleDropDownField(ModelForm):
    class Meta:
        model = MultipleSelectDropDownInput
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(MultipleDropDownField, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            # adding valueChanged dataset attribute
            visible.field.widget.attrs["data-value-changed"] = "false"
            visible.field.widget.attrs["data-model-field"] = "false"

            if visible.widget_type == "text" or visible.widget_type == "number":
                visible.field.widget.attrs["class"] = "form-control"
            elif visible.widget_type == "date":
                visible.field.widget = forms.DateInput(attrs={"class": "form-control", "type": "date"})
            elif visible.widget_type == "datetime":
                visible.field.widget = forms.DateTimeInput(attrs={"class": "form-control", "type": "datetime"})
            elif visible.widget_type == "select" or visible.widget_type == "nullbooleanselect":
                visible.field.widget.attrs["class"] = "form-select"

dynamic_forms/views.py
import json

from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView

from testapp.forms import PizzaFormNonModel
from .forms import FormModelForm
from .models import FormModel

from .view_methods import *

from .utils.form_utils import FormUtils


class IndexView(View):
    title = "Home"
    template = "dynamic_forms/index.html"

    def get(self, request):
        context = {
            'title': self.title,
        }
        return render(request, self.template, context)


class FormBuilderView(View):
    title = "New Form"
    template = "dynamic_forms/form_builder.html"

    def get(self, request, *args, **kwargs):
        form = FormModelForm()
        context = {
            'title': self.title,
            'form': form,
            'existing_form': False,
        }
        return render(request, self.template, context)

    def post(self, request, *args, **kwargs):
        pass


class FormListView(ListView):
    template_name = "dynamic_forms/forms_list.html"
    model = FormModel
    ordering = ["-created"]

    def get_context_data(self, **kwargs):
        context = super(FormListView, self).get_context_data(**kwargs)
        context["title"] = "All Forms"

        return context


class EditFormView(View):
    template = "dynamic_forms/form_builder.html"

    def get(self, request, form_id, *args, **kwargs):
        # getting the form instance
        instance = FormModel.objects.get(form_id=form_id)
        # initializing the form instance
        form = FormModelForm(instance=instance)

        context = {
            'title': instance.name,
            'form': form,
            'existing_form': True,
        }
        return render(request, self.template, context)


class RenderFormView(View):
    template = "dynamic_forms/base_form.html"
    title = "Form"

    def get(self, request, form_id, *args, **kwargs):
        preview = request.GET.get("preview", None)
        if preview:
            if preview == "true":
                preview = True
            else:
                preview = False
        form_utils = FormUtils()
        form = form_utils.build_form_for_render(form_id)
        context = {
            'title': self.title,
            'form': form,
            'preview': preview,
        }
        return render(request, self.template, context)


# ********** Fetch Requests **********
def get_form(request):
    # getting form body data
    form_data = json.loads(request.body)
    # initializing form_utils
    form_utils = FormUtils()
    field = form_data["field"]
    exists = form_data["exists"]
    input_id = form_data["inputId"]
    initial = form_data["initial"]
    if initial == "false" or initial is None:
        initial = None
    # else:
    #     initial = json.loads(initial)
    if field is not None:
        form = form_utils.get_form_fields(field=field, exists=exists, input_id=input_id, initial=initial)
        return JsonResponse({"form": form})
    else:
        return JsonResponse({"form": None, "error": "No field found"})


def get_model_form(request):
    # initialize FormUtils
    form_utils = FormUtils()
    # getting model name from url params
    model_name = request.GET.get("modelName", None)
    if model_name is not None:
        try:
            model_form = form_utils.get_model_form(model_name=model_name)
            form_fields = form_utils.get_form_fields(field=model_name, exists=False, app_model=True, model_form=model_form)
            print(form_fields)
            context = {
                "formFields": form_fields,
            }
            return JsonResponse(context, safe=True)
        except Exception as e:
            return JsonResponse({"error": str(e)})
    else:
        return JsonResponse({"error": "No model found"})


def save_form(request):
    if request.method == "POST":
        form_utils = FormUtils()
        form_data = json.loads(request.body)
        try:
            main_form = form_utils.save_form_to_db(form_data)
            return JsonResponse({"res": "success", "form_id": main_form.form_id})
        except Exception as e:
            return JsonResponse({"success": False, "error": str(e)})
    else:
        return JsonResponse({"success": False, "error": "Method not supported"})


def get_form_layout(request):
    form_id = request.GET.get("form_id", None)
    if form_id:
        instance = FormModel.objects.get(form_id=form_id)
        return JsonResponse({"res": "success", "layout": instance.layout}, status=200)
    else:
        return JsonResponse({"res": "error", "layout": None}, status=200)

dynamic_forms/templates/dynamic_forms/base_form.html
{% extends 'theme/base.html' %}
{% load static form_extras %}

{% block content %}
    {% if preview %}
        <div id="previewDiv" class="w-25 ms-3 mt-3">
            <a href="{% url 'forms:edit-form' form_id=form.id %}" class="btn btn-secondary" title="Back to form"><i class="fa-solid fa-circle-chevron-left"></i></a>
        </div>
    {% endif %}
    <div id="formDiv" class="container w-75 mt-5">
        <form class="form-container" id="form-{{ form.id }}" action="{% url 'forms:form' form_id=form.id %}" enctype="application/x-www-form-urlencoded" novalidate>
            {% csrf_token %}
            {# Rendering the form layout #}
            {% for key, value in form.form_objects.items %}
                {# getting the snippet type for determining the pathing to the correct snippet #}
                {% with template_path=value.inputType|get_snippet_path:form.input_types %}
                    {# adding the snippet and passing in the respective variables #}
                    {% include template_path with object=value input_types=form.input_types %}
                {% endwith %}
            {% endfor %}

            <button type="submit" class="btn btn-primary btn-lg">Submit</button>
        </form>
    </div>
{% endblock %}

dynamic_forms/templates/dynamic_forms/form_builder.html
{% extends 'theme/base.html' %}
{% load static %}

{% block extra_head %}
    <!-- TinyMCE scripts -->
    <script src="{% static 'tinymce/tinymce.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'django_tinymce/init_tinymce.js' %}"></script>

    <!-- Prism CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism.min.css" rel="stylesheet" />
{% endblock %}

{% block content %}
<div id="mainContent" class="d-flex m-auto mt-3 px-0 w-75 justify-content-between">

    <div id="sideNav" class="container col-3 me-3">
        <div class="nav-section d-flex">
            <button id="saveForm" type="button" class="btn btn-primary me-3" title="Save form">Save</button>
            <a id="previewForm" class="btn btn-outline-primary" role="button" type="button" title="Preview form" href="{% if existing_form %}{% url 'forms:form' form_id=form.form_id.value %}?preview=true{% else %}#{% endif %}"><i class="fa-solid fa-eye"></i></a>
        </div>

        <div id="domMessages" class="my-3 mx-auto w-auto"></div>

        <div class="nav-section">
            <button class="dropdown-caret border-bottom mb-3 btn w-100 text-start fs-4" type="button" data-bs-toggle="collapse" data-bs-target="#formSection" aria-expanded="true" aria-controls="formSection"><i class="fa-solid fa-caret-up" data-rotation="0"></i> Form Data</button>
            <div id="formSection" class="collapse show">
                <form {% if existing_form %}id="{{ form.form_id.value }}"{% endif %} class="mainForm" method="post" action="{% url 'forms:save-form' %}" data-form-type="main_form" data-form-exists="{% if existing_form %}true{% else %}false{% endif %}" novalidate>
                    {% csrf_token %}
                {% if form.non_field_errors %}
                    {{ form.non_field_errors }}
                {% endif %}

                {% for field in form %}
                    {% if not field.name == "form_id" and field.widget_type != 'hidden' %}
                        <div class="form-group mb-3">
                            <label for="{{ field.name }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                            {% if field.choices %}
                                {{ choices }}
                            {% endif %}
                        {% if field.help_text %}
                            <div class="form-text">{{ field.help_text }}</div>
                        {% endif %}
                        </div>

                        {# Field errors #}
                        {% if field.errors %}
                            {{ field.errors }}
                        {% endif %}
                    {% endif %}
                {% endfor %}
                </form>
            </div>
        </div>

        <div class="nav-section">
            <button class="dropdown-caret border-bottom mb-3 btn w-100 text-start fs-4" type="button" data-bs-toggle="collapse" data-bs-target="#inputSection" aria-expanded="false" aria-controls="inputSection"><i class="fa-solid fa-caret-up" data-rotation="0"></i> Form Inputs</button>
            <ul id="inputSection" class="nav flex-column collapse">
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="text_input"><span><i class="fa-solid fa-font"></i></span> Text Input</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="text_area"><span><i class="fa-solid fa-font"></i></span> Text Area</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="email_input"><span><i class="fa-solid fa-envelope"></i></span> Email Input</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="date_input"><span><i class="fa-solid fa-calendar-days"></i></span> Date Input</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="datetime_input"><span><i class="fa-solid fa-calendar-days"></i></span> Datetime Input</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="dropdown_input"><span><i class="fa-regular fa-square-caret-down"></i></span> Dropdown Input</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="multiple_dropdown_input"><span><i class="fa-regular fa-square-caret-down"></i></span> Multi-Select Dropdown Input</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="integer_input"><span><i class="fa-solid fa-hashtag"></i></span> Integer Input</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="decimal_input"><span><i class="fa-solid fa-hashtag"></i></span> Decimal Input</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="radio_input"><span><i class="fa-regular fa-circle-dot"></i></span> Radio Input</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="checkbox_input"><span><i class="fa-regular fa-square-check"></i></span> Checkbox Input</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="file_input"><span><i class="fa-solid fa-file"></i></span> File Input</li>
            </ul>
        </div>

        <div class="nav-section">
            <button class="dropdown-caret border-bottom mb-3 btn w-100 text-start fs-4" type="button" data-bs-toggle="collapse" data-bs-target="#sectionsSection" aria-expanded="false" aria-controls="sectionsSection"><i class="fa-solid fa-caret-up" data-rotation="0"></i> Form Sections</button>
            <ul id="sectionsSection" class="nav flex-column collapse">
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="form_row"><span><i class="fa-solid fa-rectangle-list"></i></span> Form Row</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="divider_line"><span><i class="fa-solid fa-arrows-left-right"></i></span> Divider Line</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="horizontal_rule"><span><i class="fa-solid fa-arrows-left-right"></i></span> Horizontal Rule</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="section_header"><span><i class="fa-solid fa-heading"></i></span> Section Header</li>
                <li class="nav-item fs-5 border border-secondary rounded-1 px-2 bg-dark-subtle mb-1 inputItem draggable" draggable="true" data-field-reference="text_block"><span><i class="fa-solid fa-font"></i></span> Text Block</li>
            </ul>
        </div>
    </div>

    <!-- Rough Form Outline Section -->
    <div id="formDiv" class="form-container col-9">
        <!-- Form Name - can't be deleted and mandatory -->
        <fieldset id="formHeader" class="form-section-header mb-3">
            <legend>Form Name</legend>
            <h3 id="formHeaderText" class="py-2 px-3 align-middle">{% if existing_form %}{{ form.name.value }}{% else %}{% endif %}</h3>
        </fieldset>
        <!-- The rest of the form elements will be added below -->
        <div id="formInputsDiv" class="form-objects"></div>
    </div>
</div>

<!-- for table modal -->
<div id="forTableModal" class="modal fade" tabindex="-1" aria-labelledby="forTableModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="forTableModalLabel">Warning</h1>
                <button type="button" class="btn-close cancel-btn" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Current form data will be cleared, and new inputs specific to the table will be created. Proceed with caution.
            </div>
            <div class="modal-footer">
                <button id="forTableCloseBtn" type="button" class="btn btn-secondary cancel-btn" data-bs-dismiss="modal">Go Back</button>
                <button id="forTableProceedBtn" type="button" class="btn btn-primary">Proceed</button>
            </div>
        </div>
    </div>
</div>

<!-- Form Field Templates -->
{% include 'dynamic_forms/snippets/form_fields.html' %}
<!-- Form Sections Templates -->
{% include 'dynamic_forms/snippets/form_sections.html' %}
{% endblock %}

{% block extra_js %}
    <!-- Prism.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-css.min.js"></script>

    <script>
        // making the nav top
        let sideNav = document.getElementById("sideNav");
        let siteNav = document.getElementById("siteNav");
        let domMessages = document.getElementById("domMessages");
        sideNav.style.top = `${siteNav.offsetHeight}px`;
    </script>
{% endblock %}

dynamic_forms/templates/dynamic_forms/forms_list.html
{% extends 'theme/base.html' %}

{% block content %}
    <div class="container main-top d-flex justify-content-between my-3 align-items-center">
        <h2>Forms</h2>
        <a href="{% url 'forms:new-form' %}">Add new form</a>
    </div>

    <div class="container main-middle">
        <table class="table table-striped table-bordered">
            <thead class="table-primary">
                <tr>
                    <td>Name</td>
                    <td>Created</td>
                    <td>Modified</td>
                    <td>Actions</td>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for form in object_list %}
                    <tr>
                        <td>{{ form.name }}</td>
                        <td>{{ form.created }}</td>
                        <td>{{ form.modified }}</td>
                        <td><a href="{% url 'forms:edit-form' form_id=form.form_id %}">View</a> | <a href="{% url 'forms:form' form_id=form.form_id %}?preview=true">Preview</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

dynamic_forms/templates/dynamic_forms/index.html
{% extends 'theme/base.html' %}

{% block content %}
<div class="container">
    <h2 class="border-bottom my-3">Form Builder Index</h2>
    <p>To get started, build a new form, <a href="{% url 'forms:new-form' %}">here</a>.</p>
</div>
{% endblock %}